sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

language: scala

script:
    - export RANDOM_DATA_GENERATOR_SEED=2481216758852790303
    - sbt clean coverage test
    - unset RANDOM_DATA_GENERATOR_SEED
    - sbt coverage test

after_script:
    - sbt coverageReport coveralls

scala:
  - 2.12.1
  - 2.11.8
  - 2.10.6

jdk:
  - oraclejdk8
  - oraclejdk7

env:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"

# whitelist
branches:
  only:
    - master
